GET http://localhost:3000/pets

###
GET http://localhost:3000/pets/1

###
POST http://localhost:3000/pets
Content-Type: application/json

{
  "species": "cutie",
  "name": "toe",
  "age": "5"
}

###

PATCH http://localhost:3000/pets/1
Content-Type: application/json

{
  "species": "runner"
}


###

DELETE http://localhost:3000/pets/3